apiVersion: v1
kind: Service
metadata:
  name: yelb-ui
  labels:
    app: yelb-ui
    tier: frontend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb-ip"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  ports:
  - name: ui
    port: 80
    protocol: TCP
    targetPort: 80
  - name: ui-log4j
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: yelb-ui
    tier: frontend
