---
apiVersion: v1
kind: Service
metadata:
  name: yelb-appserver
  labels:
    app: yelb-appserver
    tier: middletier
spec:
  type: ClusterIP
  ports:
  - name: appserver
    port: 4567
    targetPort: 4567
  - name: appserver-log4j
    port: 8080
    targetPort: 8080
  selector:
    app: yelb-appserver
    tier: middletier
