apiVersion: v1
kind: Service
metadata:
  name: kube-struts-svc
spec:
  type: LoadBalancer
  ports:
    - port: 8080
  selector:
    app: kube-struts-pod

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-struts-pod
spec:
  selector:
    matchLabels:
      app: kube-struts-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-struts-pod
    spec:
      containers:
        - name: kube-struts-pod
          image: quay.io/araalinetworks/struts:latest
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: docker-sock
              readOnly: false
              #imagePullSecrets:
              #- name: acr-secret
      restartPolicy: Always
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
